pattern:
  id: ^(?!(?:[0-9]+)$)([a-zA-Z]|[0-9a-zA-Z])+$
  password: ^(?=.*[a-zA-Z])(?=.*[!@#^&*])(?=.*[0-9]).{8,15}$
  email: ^[_a-zA-Z0-9-\.\_]+@[\.a-zA-Z0-9-]+\.[a-zA-Z]+$
  mobile: ^([0]{1}[0-9]{2})-([1-9]{1}[0-9]{2,3})-([0-9]{4})$
  hpNo: ^([0]{1}[0-9]{1,2})-([1-9]{1}[0-9]{2,3})-([0-9]{4})|(15|16|18)(00|70|44|66|77|88)-[0-9]{4}$
  english: ^[a-zA-Z]+$
  korean: ^[가-힣]+$
  number: ^[0-9]+$
  name: ^[가-힣]+$
  date: ^\d{4}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])$  #2022-03-22 형태
  ip: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$
