spring.config.activate.on-profile: local, dev, stg, prod
#MybatisConfig.java에서 사용할 설정
mybatis-config:
  type-handlers-package: com.kap.core.dto.*
  mapper-location: classpath*:mappers/**/*.xml
  config-location: classpath:mybatis.xml
  transaction-package-nm: execution(* egovframework.com..*Impl.*(..)) or execution(* com.kap..*Impl.*(..))
---
spring.config.activate.on-profile: local
spring:
  db:
    datasource:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mysql://192.168.0.12:3306/kap?serverTimezone=UTC&useUnicode=true&charcterEncoding=utf8&useSSL=false&allowMultiQueries=true
      username: kap
      password: dnfntk1##
      ##Db jndi 명
      jndi-name:
---
spring.config.activate.on-profile: dev
spring:
  db:
    datasource: jdbc/kapDS
      ##Db jndi 명

---
spring.config.activate.on-profile: prod
spring:
  db:
    datasource: jdbc/kapDS
      #Db jndi 명

