---
spring.config.activate.on-profile: local, dev
app:
  #메일 설정
  mail:
    senderMail: kapkorea@kapkorea.org
    senderHp: 0232712681
    sender_name: 자동차부품산업진흥재단
    username: kapkorea
    key: 9T2r3AVGeh7rslu
    mail_url: https://directsend.co.kr/index.php/api_v2/mail_change_word
    sms_url: https://directsend.co.kr/index.php/api_v2/sms_change_word
---
spring.config.activate.on-profile: stg
app:
  #메일 설정
  mail:
    senderMail: kapkorea@kapkorea.org
    senderHp: 0232712681
    sender_name: 자동차부품산업진흥재단
    username: kapkorea
    key: 9T2r3AVGeh7rslu
    mail_url: https://directsend.co.kr/index.php/api_v2/mail_change_word
    sms_url: https://directsend.co.kr/index.php/api_v2/sms_change_word
---
spring.config.activate.on-profile: prod
app:
  #메일 설정
  mail:
    senderMail: kapkorea@kapkorea.org
    senderHp: 0232712681
    sender_name: 자동차부품산업진흥재단
    username: kapkorea
    key: 9T2r3AVGeh7rslu
    mail_url: https://directsend.co.kr/index.php/api_v2/mail_change_word
    sms_url: https://directsend.co.kr/index.php/api_v2/sms_change_word