spring.config.activate.on-profile: local, dev
domain:
  host: 127.0.0.1
  port: 9011
server:
  port: 9012
  max-http-header-size: 40MB
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: dnfntk1##
    key-alias: bns-ssl
  tomcat:
    additional-tld-skip-patterns: "*.jar"
    max-http-form-post-size: 104886080
    max-swallow-size: 104886080
  servlet:
    session:
      timeout: 3600
      cookie:
        name: KAP_LOCAL_ADMIN_JSESSIONID
---
spring.config.activate.on-profile: stg
domain:
  host: devapi.therailntel.com
  port: 20141
server:
  servlet:
    session:
      timeout: 3600
      cookie:
        name: ADMIN
---
spring.config.activate.on-profile: prod
domain:
  host: api.therailntel.com
server:
  servlet:
    session:
      timeout: 3600
      cookie:
        name: ADMIN
