spring:
  config:
    import:
      - classpath:/application-domain.yml
      - classpath:/application-rules.yml
      - classpath:/application-db.yml
      - classpath:/application-mail.yml
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
      static-path-pattern: /static/**
    pathmatch:
      matching-strategy: ant_path_matcher
    resources:
      static-location: classpath:/static/
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 42MB  # 파일 뿐만 아니라 제목, 내용등도 같이 전송되기때문에 file size보단 크게 설정
    max-http-header-size: 4000000
  #OBJECTMAPPER CAMELCASE
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
  web:
    resources:
      add-mappings: true


api :
  gpc:
    end-point: https://gpc.hyundai.co.kr/mngwserc
    key: A5Z0A4B9B5T4
    secret: bc125IJyf96M1LTCsEq6a8PntjFn8Dpc
  kap:
    end-point: https://127.0.0.1:9012
    key: N5Z0A4B9A5T4
    secret: hV127IJyf96M1LTAsEq6a8PntjFK9DpC

---
#spring :
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username : dev@easymedia.net
#    password : dnfntk1##
#    properties :
#      mail :
#        smtp :
#          auth : true
#          timeout : 5000
#          starttls :
#              enable : true

---

#강제 로그인 여부
app:
  is-login: false
  #사이트 구분
  site-gubun: admin
  #발신자 이메일
  from-mail: dev@easymedia.net
  #사용자 도메인1
  user-domain: https://127.0.0.1:9014
  #관리자 도메인
  admin-domain: https://127.0.0.1:9012
  site:
    #html title
    name: KAP
  file:
    #파일 업로드 물리 경로
    upload-path: D:/IdeaProjects/worksapace/kap_upload
    #파일 업로드 가능 확장자
    fileExtns: jpg,jpeg,gif,png,bmp,mp4,webm,wmv,avi,mkv,pdf,ppt,pptx,xls,xlsx,doc,docx,dox,hwp,hwpx,txt,zip
    fileExtnsPdf: pdf, ppt, pptx, doc, docx, xls, xlsx

    imageExtns: jpg,jpeg,png
    videoExtns: mp4,webm,wmv,avi,mkv
    #파일 업로드 크기
    max-size: 104857600
    #썸네일 사이즈 관련
    #메인 비주얼 PC
    mainVslPcSize : 1920 x 1080
    #메인 비주얼 Mbl
    mainVslMblSize : 390 x 675
    #상생사업 영역
    cxstnSize : 700 x 675
    #Trend 레이어 영역
    #교육사업
    trendEduSize : 337 x 210
    #컨설팅사업
    trendCnstgSize : 337 x 480
    #상생사업
    trendCxstnSize : 480 x 480
    #메인 팝업 PC
    mainPopPcSize : 440 x 460
    #메인 팝업 Mbl
    mainPopMblSize : 350 x 365
    #교육과정 썸네일
    eduThumSize : 337 x 210
    #위원관리 사진 사이즈
    cmssrImgSize : 337 x 386
    #재단소식 및 뉴스레터 Pc
    bdThumPcSize : 337 x 210
    #재단소식 및 뉴스레터 Mbl
    bdThumMblSize : 170 x 106


log4jdbc:
  dump:
    sql:
      maxlinelength: 0
  spylogdelegator:
    name: net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator

logging:
  level:
    root: info
    jdbc:
      connection: off
      sqlonly: off
      sqltiming: debug
      audit: off
      resultset: off
      resultsettable: off
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(%5p) %clr(%-60(%logger{0}.%M\\(%L\\))){cyan} %clr(:){faint} %m%n%wEx"
    #console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr([%10t]){faint} %clr(%-60(%logger{39}.%M\\(%L\\))){cyan} %clr(:){faint} %m%n%wEx"
    #console: "%d{yyyy-MM-dd HH:mm:ss} [%-5p] [%F]%M\\(%L\\) : %m%n"
---
spring.config.activate.on-profile: dev
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p ${PID:- } [%10t] %-60(%logger{39}.%M\\(%L\\)) : %m%n%wEx"
app:
  is-login: false
nice :
  client-id : 1d9b7bb5-b3da-4b64-a852-003b3b5615f6
  client-secret : 5402455ebfb7f2d9178213d312c7d206756db5e
  product-id : 2101764012
  url : https://svc.niceapi.co.kr:22001
  enc-product-id : 2101979031

api:
  gpc:
    end-point: https://gpc.hyundai.co.kr/mngwserc
    key: A5Z0A4B9B5T4
    secret: bc125IJyf96M1LTCsEq6a8PntjFn8Dpc
  kap:
    end-point: http://kap.easymedia.kr
    key: N5Z0A4B9A5T4
    secret: hV127IJyf96M1LTAsEq6a8PntjFK9DpC

---
spring.config.activate.on-profile: prod

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p ${PID:- } [%10t] %-60(%logger{39}.%M\\(%L\\)) : %m%n%wEx"
nice :
  client-id : 1d9b7bb5-b3da-4b64-a852-003b3b5615f6
  client-secret : 5402455ebfb7f2d9178213d312c7d206756db5e
  product-id : 2101764012
  url : https://svc.niceapi.co.kr:22001
  enc-product-id : 2101979031

api:
  gpc:
    end-point: https://gpc.hyundai.co.kr/mngwserc
    key: A5Z0A4B9B5T4
    secret: bc125IJyf96M1LTCsEq6a8PntjFn8Dpc
  kap:
    end-point: http://192.168.0.14
    key: N5Z0A4B9A5T4
    secret: hV127IJyf96M1LTAsEq6a8PntjFK9DpC

#강제 로그인 여부
app:
  is-login: false
  user-domain: https://mng.kapkorea.org
  file:
    #파일 업로드 물리 경로
    upload-path: /uploadfiles
    #파일 업로드 가능 확장자
    fileExtns: jpg,jpeg,gif,png,bmp,mp4,webm,wmv,avi,mkv,pdf,ppt,pptx,xls,xlsx,doc,docx,dox,hwp,hwpx,txt,zip
    imageExtns: jpg,jpeg,gif,png,bmp
    videoExtns: mp4,webm,wmv,avi,mkv
    #파일 업로드 크기
    max-size: 104857600
    #템플릿 경로
    template-file-path: /home/ec2-user/app/client/webapps/WEB-INF/template/