spring:
  config:
    import:
      - classpath:/application-domain.yml
      - classpath:/application-rules.yml
      - classpath:/application-db.yml
      - classpath:/application-mail.yml
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
      static-path-pattern: /static/**
    pathmatch:
      matching-strategy: ant_path_matcher
    resources:
      static-location: classpath:/static/
  servlet:
    multipart:
      enabled: true
      max-file-size: 40MB
      max-request-size: 42MB  # 파일 뿐만 아니라 제목, 내용등도 같이 전송되기때문에 file size보단 크게 설정
  #OBJECTMAPPER CAMELCASE
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
  web:
    resources:
      add-mappings: true

nice :
  return-url-adm : http://mng.kap.easymedia.kr
  return-url-user : http://kap.easymedia.kr

#강제 로그인 여부
app:
  is-login: false
  #사이트 구분
  site-gubun: front
  #발신자 이메일
  from-mail: dev@easymedia.net
  #사용자 도메인1
  user-domain: https://127.0.0.1:9014
  #관리자 도메인
  admin-domain: https://127.0.0.1:9012
  site:
    #html title
    name: KAP
  file:
    #파일 업로드 물리 경로
    upload-path: D:/project/kap_git
    #파일 업로드 가능 확장자
    fileExtns: jpg,jpeg,gif,png,bmp,mp4,webm,wmv,avi,mkv,pdf,ppt,pptx,xls,xlsx,doc,docx,dox,hwp,txt,zip
    imageExtns: jpg,jpeg,gif,png,bmp
    videoExtns: mp4,webm,wmv,avi,mkv
    #파일 업로드 크기
    max-size: 41943040


log4jdbc:
  dump:
    sql:
      maxlinelength: 0
  spylogdelegator:
    name: net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator

logging:
  level:
    root: info
    jdbc:
      connection: off
      sqlonly: off
      sqltiming: debug
      audit: off
      resultset: off
      resultsettable: off
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(%5p) %clr(%-60(%logger{0}.%M\\(%L\\))){cyan} %clr(:){faint} %m%n%wEx"
    #console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr([%10t]){faint} %clr(%-60(%logger{39}.%M\\(%L\\))){cyan} %clr(:){faint} %m%n%wEx"
    #console: "%d{yyyy-MM-dd HH:mm:ss} [%-5p] [%F]%M\\(%L\\) : %m%n"
---
spring.config.activate.on-profile: stg, dev
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p ${PID:- } [%10t] %-60(%logger{39}.%M\\(%L\\)) : %m%n%wEx"

app:
  is-login: false
---
spring.config.activate.on-profile: dev
spring :
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
    thymeleaf:
      cache: false

app:
  is-login: false