
server-status : local

nice :
  client-id : 1d9b7bb5-b3da-4b64-a852-003b3b5615f6
  client-secret : 5402455ebfb7f2d9178213d312c7d206756db5e
  product-id : 2101764012
  url : https://svc.niceapi.co.kr:22001
  enc-product-id : 2101979031
  return-url-adm : https://127.0.0.1:9012
  return-url-user : https://127.0.0.1:9014
#강제 로그인 여부
app:
  file:
    #파일 업로드 물리 경로
    upload-path: D:/project/kap_git
    #파일 업로드 가능 확장자
    fileExtns: jpg,jpeg,gif,png,bmp,mp4,webm,wmv,avi,mkv,pdf,ppt,pptx,xls,xlsx,doc,docx,dox,hwp,txt,zip
    imageExtns: jpg,jpeg,gif,png,bmp
    videoExtns: mp4,webm,wmv,avi,mkv
    #파일 업로드 크기
    max-size: 41943040
    #템플릿 경로
    template-file-path: D:\EGOVFRAME\project\2023\kap\admin\src\main\webapp\WEB-INF\template\
#    template-file-path: D:\kap-git\client\src\main\webapp\WEB-INF\jsp\template\